### ISSUE TITLE
Implement variance analysis

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#101]
This will be important to simplify inferred types further.

**Comment by twitu** [comment]
We're trying to create a method here say `getVariance` in `Typer.scala`. This method will find the variance of an expression for all it's type parameters (inputs and outputs).

As discussed on discord the following class is a good way to encode variance information.

```
case class VarianceInfo(isCovariant: Bool, isContravariant: Bool), which would start as VarianceInfo(isCovariant = true, isContravariant = true) (i.e., bivariant)
```

Since variance will be used for further simplification this analysis should be done on the internal representation of types i.e. `SimpleType` and `PolymorphicType`.

So tenatively the method might have the following signature.

```
getVariance(ty: TypeScheme): List[BoundedVariable -> VarianceInfo]
```

**Comment by LPTK** [comment]
It would make more sense to make it `computeVariances(ctx: Ctx)`, because it will have to figure out the variance of all related classes (which may refer to each other recursively) in a type hierarchy at once, using a fixed point. The `computeVariances` method would leave those types that already have their variance info untouched, and would set the variance info for the others.

**Comment by twitu** [comment]
Ohk so tentatively `computeVariances(ctx: Ctx, typeVariances: HashMap[BoundedVariable, VarianceInfo]): Unit` takes the context and free type variables. Recursively keeps updating the variance info and stops when there is no further change. The hash map could be part of `Ctx` as well, if that's better design.

These are the rules I can think off to compute the variance -
* (arg: a) -> b => a is contravariant, b is covariant
* Box[T] => T is invariant
* lower..upper => covariant on upper, contravariant on lower
* contra & contra => co
* contra & co => contra
* co & co => co
* invariant & {contra, co} => invariant
* bivariant & {contra, co} => {contra, co}

**Comment by LPTK** [comment]
> * (arg: a) -> b => a is contravariant, b is covariant
> * Box[T] => T is invariant
> * lower..upper => covariant on upper, contravariant on lower

This is only true in positive positions. Obviously they reverse in the opposite polarity.

The real difficulty here is what to do when you arrive at something like `C[S, T, ...]`. You can't recurse into analyzing `S`, `T`, ... without knowing the parameter variances of `C`. But to compute these parameter variances, you may need to look at other occurrences of `C[S', T', ...]` types.

So you probably need to keep these `C[S, T, ...]` traversals "on hold" while you accumulate the rest of the variance information. Then you revisit those that may have changed based on the new information you found. For example, if you saw `A` in positive position in `class C[A, B, ...]`, you need to mark `C`'s first param as *not contravariant* (so if its current state is bivariant, you change it to covariant; if it's contravariant, you change it to invariant), and this should then trigger you to revisit the `C[S, T, ...]` we had put on hold, meaning that you should analyze `S` at positive polarity since it's currently believed to be at most covariant (but possibly invariant).

**Comment by twitu** [comment]
What if we have a commutative and associatve operation to combine the variances. For e.g. this

```
contra x contra => co
contra x co => contra
co x co => co
invariant x {contra, co} => invariant
bivariant x {contra, co} => {contra, co}
```

Feels very much like integer multiplication, co => +, contra => -, inv => 0, bi => +1. Being commutative and associative the order does not matter, we could go down one C[S, T..] and apply whatever we learn. If we encounter another C[S', T'...] we again apply whatever we learn to existing variance of say S'. And we keep doing this till, just like you mentioned, we'll reached the fixed point when there'll be no more change. Wouldn't this remove the need to pause the traversals?

Now looking at the internal types to see which ones will contribute to variance. I can see is that any `SimpleType` with universally qualified type variables is a wrapped in a `PolymorphicType`. So we consider these SimpleTypes now among these (using Scala notation) -

* `TypeBounds[-lb, +ub]`
* `NegType[t]`
* `ComposedType[a, b]`
* `FieldType[-lb, +ub]`
* `TypeRef[T1, T2, ...]`
*  `FunctionType[-in, +out]`
* `Without[T]`

**Comment by LPTK** [comment]
Example given in group meeting:

```
class D[X]
  method M1: C[X]
  method M2: ... X ...

class C[A]
  method M1: D[C[int]]
  method M2: ... A ...
```

**Comment by LPTK** [comment]
- [ ] TODO: Raise a warning when a type parameter is found to be bivariant – something like "`type parameter T is irrelevant and could be removed`".
