### ISSUE TITLE
NodeJS REPL integration swallows errors

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#106]
As we've seen before, such as here: https://github.com/hkust-taco/mlscript/issues/65#issuecomment-1107447111

When there is a top-level syntax error in the NodeJS REPL, nothing in the test output indicates that anything is wrong. Even the `:ShowREPL` option does not show the syntax error output.

We should have a way of more effectively debugging such issues. Ideally by properly reporting the error, though that may be annoying to implement. At the very least, `:ShowREPL` should let us know what's going on by printing all the NodeJS output.

**Comment by LPTK** [comment]
BTW @chengluyu isn't this fixed now?

**Comment by chengluyu** [comment]
Yes. It’s fixed. Note that `console.log` still outputs nothing because it's mixed in the output. For example,

```
()
//│ res: ()
//│    = []

:escape
def console: { log: anything -> undefined }
//│ console: {log: anything -> undefined}
//│        = <missing implementation>

:ShowRepl
console.log "hello"
//│ ┌ Block at Repro.mls:9
//│ ├── No prelude
//│ └─┬ Query 1/1
//│   ├── Prelude: <empty>
//│   ├── Code: res = console.log("hello");
//│   ├── Intermediate: hello
//│ undefined
//│   └── Reply: [success] undefined
//│ res: undefined
//│    = undefined
```

But as you commented in #65, Tony made a helper function at https://github.com/hkust-taco/mlscript/commit/ecca9d8d5072723b575496dac151067292d5129e

**Comment by LPTK** [comment]
Ok, thanks for the follow-up.
