### ISSUE TITLE
Implement virtuality and constructor restrictions

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#173]
- [x] allow `fun` and `val` members to be declared `virtual`; a signature without an implementation is considered virtual automatically
 - [x] check that overridden `fun`s and `val`s are virtual
 - [x] forbid uses of `this` in constructors, including a class' initialization statements in the body and `val` RHSs
 - [x] make an exception to the above for each _final_ (ie non-virtual) member which either is a `val` _or_ is a `lazy val` or a `fun` that doesn't itself transitively use this

**Comment by NeilKleistGao** [comment]
I think all tasks are finished.
