### ISSUE TITLE
Support "this types"

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#20]
Would actually be quite straightforward to support. Example:

```scala
class A
  method Foo: Int -> this

class B: A
  method Foo n = console.log n; this

a = B{}
a.Foo 1 // : B

b: A = a
b.Foo 1 // : A
```

**Comment by chengluyu** [comment]
Is `method Foo n = console.log n; this` the unimplemented block syntax?

**Comment by LPTK** [comment]
Oh yeah I guess it's not yet supported in the current parser. It's equivalent to `let _ = console.log n in this`.

**Comment by LPTK** [comment]
As discussed in the group meeting, it's probably better to make `this` rigid.

At first we implemented it as  a flexible type variables, which allowed to refine the type of `this` as needed, but this has two drawbacks:

1. it generates method types that can't easily be translated to TS (which does not have a construct for refining `this`)

2. it can lead to inferring impossible `this` types (typically, containing things that collapse to `nothing`), delaying the reporting of some errors
