### ISSUE TITLE
Handle polarity of `TypeRef` in `extrude`

### ISSUE THREAD

**Issue by fo5for** [hkust-taco/mlscript#24]
https://github.com/hkust-taco/mlscript/blob/193deba9ab7b3358683405b91fdcb2f2f4dc1c54/shared/src/main/scala/mlscript/ConstraintSolver.scala#L399

`ConstraintSolver.extrude` currently ignores the polarity of the type arguments in `TypeRef`s, which is unsound. This can be fixed by implementing polarity analysis, or by expanding the `TypeRef` before extrusion.

**Comment by LPTK** [comment]
I've actually fixed this as part of #41 already. See: https://github.com/hkust-taco/mlscript/pull/41/files#diff-f4d221f395e56fd5ce982b8b65b9d545c499c267f8ccb94d6a3dfc95eebbcad2R405-R411
