### ISSUE TITLE
`checkRegular` returns false negatives

### ISSUE THREAD

**Issue by fo5for** [hkust-taco/mlscript#26]
```scala
class Foo[A]: { value: A }
class Bar[A]: Foo[Foo[A]]
//│ Defined class Foo
```

The `TypeDef` of `Bar` is not registered to the context even though no error are emitted. A quick inspection reveals that `checkRegular` returns `false` in this case.

**Comment by LPTK** [comment]
Good catch! The issue was that we were checking for equal type arguments for all traversed type definitions, instead of just the one under consideration.
