### ISSUE TITLE
Add JS tests

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#34]
The JS code-gen has become quite non-trivial and needs to be tested. We should update the diff-tests to also compile and run the JS, probably by shelling out to `node`.

- [x] Make sure to import the tests documented in https://github.com/hkust-taco/mlscript/pull/30

**Comment by LPTK** [comment]
While we're at it, there are some cases where JS code-gen results in wrong JS code, such as: `fun {x = 1} -> 0`. Would be good to solve them and add tests for them (it's probably not worth opening an issue for them at this point).

EDIT: also this one: `fun ((x, y)) -> x`

**Comment by LPTK** [comment]
> * [ ]  Make sure to import the tests documented in [JavaScript code generation for methods #30](https://github.com/hkust-taco/mlscript/pull/30)

@chengluyu You had forgotten to add tests for this stuff. I've added them in https://github.com/hkust-taco/mlscript/commit/7c4b70cda9d3ed0326e2199dc6a79646ad387504.

**Comment by LPTK** [comment]
> While we're at it, there are some cases where JS code-gen results in wrong JS code, such as: `fun {x = 1} -> 0`. Would be good to solve them and add tests for them (it's probably not worth opening an issue for them at this point).
> 
> EDIT: also this one: `fun ((x, y)) -> x`

@chengluyu You also forgot to add tests for that. Added in https://github.com/hkust-taco/mlscript/commit/7d04016c9c702ccc8a896728b28e39e638b5839f.

You should be more careful when closing an issue, especially when it clearly has uncompleted items/tasks.

**Comment by chengluyu** [comment]
> > While we're at it, there are some cases where JS code-gen results in wrong JS code, such as: `fun {x = 1} -> 0`. Would be good to solve them and add tests for them (it's probably not worth opening an issue for them at this point).
> > EDIT: also this one: `fun ((x, y)) -> x`
> 
> @chengluyu You also forgot to add tests for that. Added in [7d04016](https://github.com/hkust-taco/mlscript/commit/7d04016c9c702ccc8a896728b28e39e638b5839f).
> 
> You should be more careful when closing an issue, especially when it clearly has uncompleted items/tasks.

Thanks for pointing this out! It was a big oversight!
