### ISSUE TITLE
JS code-gen is unhygienic

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#45]
Example:
```ts
def f x = case 1 of { 1 -> x }
```

Generates, for the body of `f`:
```js
(x) => (function (x) { if (x == 1) { return x; } throw new Error("non-exhaustive case expression"); })(1)
```

The normal way of dealing with this is the "gensym" approach, for "generating symbols". For every name x you want to use, you call gensym("x"), and a new name distinct with every other name in the program is picked.

We could also have a more local version that only picks names different from names currently in scope, which would avoid generating too many harder-to-read unique names.

**Comment by chengluyu** [comment]
Yes. I’m aware of this problem, too. My plan is to track current JavaScript scope during transpiling. The scope object provides name allocation and renaming functionalities.
