### ISSUE TITLE
Generate TypeScript type definition files from MLscript modules

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#57]
This would allow reusing MLscript definitions from TypeScript.

I don't foresee any major difficulty to implement this, although the handling of recursive types will need the introduction of auxiliary type alias definitions on the TS side, as TS does not support "inline" recursive types such as `(int -> ‘a) as 'a`.

**Comment by twitu** [comment]
`syntax.scala` contains the relevant types that need to be mapped to typescript types. This is the mapping I could come up with and there are a couple of places I have questions.

| mlscript type | typescript type | comments |
| ------------- | --------------- | -------- |
| Union(lhs: TypeA, rhs: TypeB) | `TypeA \| TypeB` | type union is directly supported |
| Inter(lhs: TypeA, rhs: TypeB) | TypeA & TypeB | type intersection is directly supported |
| Function(lhs: TypeA, rhs: TypeB) | (a: TypeA) => TypeB | function from lhs type to rhs |
| Record(fields: List[VarN -> TypeN]) | { VarA: TypeA, VarB: TypeB ..} | converts list of field names and types to  dictionary style |
| Tuple(fields: List[Opt[Var] -> TypeN]) | [TypeA, TypeB, ...] | converts tuple to fixed length list with specified types which is how typescript supports tuples |
| Recursive(uv: TypeVarA, body: TypeA) | TODO | TODO |
| AppliedType(base: TypeName, targs: List[Type]) | TODO | TODO |
| Neg(base: TypeA) | type NewTypeA<T> = T extends TypeA ? never : T | Check if type extends negative type then return never/bottom or the type itself |
| Rem(base: TypeA, names: List[VarN]) | Omit<TypeA, { VarA, VarB, ... }> | [Omit](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type) makes it possible remove properties |
| Bounds(lb: Type, ub: Type) | TODO | TODO |
| WithExtension(base: TypeA, rcd: RecordA) | TypeA & RecordA | extend through intersection |
| Top | unknown | top type in typescript |
| Bot | never | bottom type in typescript |
| TypeVar(val identifier: Int \/ Str, nameHint: Opt[Str]) | TODO | TODO |
| PolyType(targs: List[TypeName], body: Type) | TODO | TODO |

Q0. Lower bounds are not supported in typescript [issue](https://github.com/Microsoft/TypeScript/issues/14520), how to represent a `Bounds` type in typescript?

Q1. How does TypeVar (Type variable?) use it's arguments, what is it doing?

Q2. Does PolyType here refer to a parameteric type? That is ideally used in together with AppliedType?

**Comment by LPTK** [comment]
That's a good start! I have updated your table below, with updates in bold:

| mlscript type | typescript type | comments |
| ------------- | --------------- | -------- |
| Union(lhs: TypeA, rhs: TypeB) | TypeA \| TypeB | | type union is directly supported |
| Inter(lhs: TypeA, rhs: TypeB) | TypeA & TypeB | type intersection is directly supported |
| Function(lhs: TypeA, rhs: TypeB) | (a: TypeA) => TypeB | function from lhs type to rhs |
| Record(fields: List[VarN -> TypeN]) | { VarA: TypeA, VarB: TypeB ..} | converts list of field names and types to  dictionary style |
| Tuple(fields: List[Opt[Var] -> TypeN]) | [TypeA, TypeB, ...] | converts tuple to fixed length list with specified types which is how typescript supports tuples |
| Recursive(uv: TypeVarA, body: TypeA) | **Aux_42[S, T, U, ...]** | **Aux_n types are introduced along side translated signatures** |
| AppliedType(base: TypeName, targs: List[Type]) | **Foo<S, T, U, ...>** | |
| Neg(base: TypeA) | type NewTypeA<T> = T extends TypeA ? never : T | Check if type extends negative type then return never/bottom or the type itself |
| Rem(base: TypeA, names: List[VarN]) | Omit<TypeA, { VarA, VarB, ... }> | [Omit](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type) makes it possible remove properties |
| Bounds(lb: Type, ub: Type) | **ub in positive position; lb in negative position; not sure otherwise** | TODO: see what to do for Bounds in invariant position |
| WithExtension(base: TypeA, rcd: RecordA) | **[same as Rem and With]** | |
| Top | unknown | top type in typescript |
| Bot | never | bottom type in typescript |
| TypeVar(val identifier: Int \\/ Str, nameHint: Opt[Str]) | A_n |  |
| PolyType(targs: List[TypeName], body: Type) | **<A1, A2, ...>T** | probably only valid when T is a function types in TS |

Note that `WithExtension` represents things like `T with { x = S }`, which is equivalent to `T\x & S` (where `T\x` is a field removal type).

> Q0. Lower bounds are not supported in typescript [issue](https://github.com/Microsoft/TypeScript/issues/14520), how to represent a `Bounds` type in typescript?

Ah yes that's annoying. We'll probably have to represent lower bounds through normal (non-lower-bounded) type variables along with type unions. We can discuss later how to do this.

> Q1. How does TypeVar (Type variable?) use it's arguments, what is it doing?

There are two ways of uniquely identifying a type variable. Either by a name (if it appears under this name in the source) or by a unique id (if it was generated during type inference). For TS code generation, you should probably use logic similar to what's done in https://github.com/hkust-taco/mlscript/blob/292e44b311ce7ea4ae5aec7dc3c54d0a967b10f8/shared/src/main/scala/mlscript/helpers.scala#L83-L115 (the code could probably be shared) to generate nice but non-clashing names.

> Q2. Does PolyType here refer to a parameteric type? That is ideally used in together with AppliedType?

No, it represents a polymorphic type (not a higher-kinded one). For example, in TS `<A>(x: A) => A` is a polymorphic function type, taking a type parameter. It will be applied in terms (probably implicitly), not in types (so, not through AppliedType).

**Comment by twitu** [comment]
The entry point for function that generates typescript type definitions, say `typeGen: List[TypeDef] => SoureCode`, would take the list of type definitions from the output of `Pgrm.desugared`. It would then iteratively convert the definitions to `SourceCode` which can then be converted to an exportable string representation.

Each `TypeDef` contains all the information needed to convert it to a typescript type. The field `body: Type` actually determines which mlscript type the type definition instance represents.

Another important field is the `TypeDefKind` which tells if the type is for a class, trait or a type alias. The above table currently only represents the mapping for type aliases.

**Comment by LPTK** [comment]
> The above table currently only represents the mapping for type aliases.

Not sure what you mean. The table shows how to convert any type expression. Say, for instance, `number -> List[string]` would be converted to `(_: number) => List<string>`. OTOH `TypeDef` is used to represent things like `type Alias = number -> List[string]`, which will be translated to `type Alias = (_: number) => List<string>`.

> take the list of type definitions from the output of `Pgrm.desugared`. It would then iteratively convert the definitions to `SourceCode`

Actually, the main idea is to first perform type inference. Then, what we're really interested in converting to Ts is the resulting `Type` inferred for each `def` – the one created here from `ty_sch` by expanding the typer's internal inferred type representation: https://github.com/hkust-taco/mlscript/blob/7d04016c9c702ccc8a896728b28e39e638b5839f/shared/src/test/scala/mlscript/DiffTests.scala#L368

Even classes need type inference info to be translated correctly, since their methods may not always have type annotations.

**Comment by twitu** [comment]
> Actually, the main idea is to first perform type inference.

Oh ok, I had mis-assumed that after type inference/type checking `Pgrm` instance would store the type information for each term in a look up table. Would it be a good idea to decouple the type inference step from the output step? It can be a separate task/issue to store this information.

And my understanding of the desugared program was incorrect. Information for all class, trait and type alias is stored as `TypeDefKind`, while for methods we use `MethodDef`.

Classes, traits, and methods are associated with the terms and types that make up their body and type signature respectively. For e.g. for methods -

```
final case class MethodDef[RHS <: Term \/ Type](
  rec: Bool,
  prt: TypeName,
  nme: TypeName,
  tparams: List[TypeName],
  rhs: RHS,
```

The RHS field contains the term that makes up the body of the method and it's type.

Finally the `Ls[Term]` that is returned by `desugared` program are actually terms that are defined in the global scope so they are not part of any user defined class, method, trait.

All these 4 "things" classes, traits, methods (inside classes) and, terms that are defined globally will have to be converted to Ts types and exported in the declaration file.

**Comment by LPTK** [comment]
> Would it be a good idea to decouple the type inference step from the output step?

What do you mean by that? Type inference mostly lives in `Typer` and `ConstrainSolver`, which are not coupled with output.

> Information for all class, trait and type alias is stored as `TypeDefKind`

`TypeDefKind` is just essentially an enum. Perhaps you meant `TypeDef`?

> The RHS field contains the term that makes up the body of the method and it's type.

It's actually _either_ a body or a type. It's used to encode either a declaration `def f: T` or a definition `def f = t`. In the latter case, we don't have a type yet (type inference is needed to get that type).

**Comment by twitu** [comment]
Couple of challenges when generating function types.

```scala
// higher order function
def g f y = f y + 1
//│ Recons: ((((α15) -> int<number>)) -> ((α15) -> int<number>))
//│ g: ('a -> int) -> 'a -> int
//│ ts: (arg0: (arg1: type α15) => int) => (arg0: type α15) => int
```

Some argument types are actually type variables (`TypeVar`) created during type inference. To create a valid typescript type they'll need to be resolved in possibly two ways for e.g. -
* replace `α15` with it's type `int<number>`
* create a type alias above/below like `type α15 = number` above/below the actual function type

Both approaches will require the `toTsType :: Type -> SourceCode` method to take the environment context as well, so that it can resolve the type variables.
 
```scala
// multiple parameters
def f x y = x + y
//│ f: int -> int -> int
//│ ts: (arg0: int) => (arg0: int) => int
```
This works but giving same argument names is confusing. This happens because it is treated as a curried function i.e. (int => (int => int)). The inner function is resolved first and given `arg0` name, but since `toTsType` is stateless this information is not given to the outer function which again gives `arg0` name.

Fixing this will require maintaining state of existing variables defined or by passing environment context which would have the names of the parameters from the function expression, for e.g. in this case `(x: int) => (y: int) => int`.

Another point to note is that the underlying javascript function will be curried overall parameters and can only be called like `f(1)(2)`.

**Comment by LPTK** [comment]
> * replace `α15` with it's type `int<number>`

Why do you think `α15` is `int<number>` or `number`? If it was, the type inference engine would just output `number`, not  `α15`. This type variable is here because of parametric polymorphism, and it should be a type variable in TS too...

**Comment by twitu** [comment]
Some points from our discussion today.

> //│ Recons: ((((α15) -> int<number>)) -> ((α15) -> int<number>))
Indicates that `α15` is a type variable and the function is actually parametric over it's type. As in -

```
type f<T> = (arg0: (arg1: T) => int) => (arg0: T) => int
```

This information that the outer function needs a type parameter can be found at the outer function level itself by creating a `ShowCtx` instance which holds the type parameters needed for that particular type.

Any other state like one to create unique argument names can be solved by threading a mutable state through the `toTsType` method.

**Comment by LPTK** [comment]
> Any other state like one to create unique argument names can be solved by threading a mutable state through the `toTsType` method.

Actually you don't even need to thread through anything. Just have a local recursive definition that captures a local `var` or mutable collection. As in `def foo(...) = { var state = ... ; def impl(...) = ... impl... ; impl(...) }`.
