### ISSUE TITLE
Support `undefined`, `null`, and related operations/features

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#98]
First step: support `undefined`

- add a new syntax form `UnitLit(undefinedOrNull: Bool) extends Lit`

- make `undefined` a keyword in MLParser, parsing as `UnitLit(true)`

- make `undefined` a builtin type in Typer.scala

- update Typer's typeTerm to assign type undefined to keyword undefined

- update JS code generation in JSBackend to account for undefined

**Comment by mahzoun99** [comment]
Umm, What is the next step?

**Comment by LPTK** [comment]
Oh I think this issue should have been closed by https://github.com/hkust-taco/mlscript/pull/105, right? It was a mistake not to link the PR with the issue. Or do you still see anything that's missing?

**Comment by mahzoun99** [comment]
Yes, I agree. I think it is done 🤔
